stages:
  - mirror

mirror_to_github:
  stage: mirror
  image: alpine:latest
  script:
    - apk add --no-cache git
    - git config --global user.email "lalit.logical@gmail.com"
    - git config --global user.name "Lalit Kumar Maurya"
    - echo "https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/$GITHUB_USERNAME/$CI_PROJECT_NAME.git"
    - git remote add github https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/$GITHUB_USERNAME/$CI_PROJECT_NAME.git
    - git push --mirror github
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"'
