entryPoints:
  web:
    address: ":80"

providers:
  file:
    filename: "/etc/traefik/dynamic.yml"
    watch: true

api:
  dashboard: true

serversTransport:
  forwardingTimeouts:
    dialTimeout: 15s
    responseHeaderTimeout: 15s
    idleConnTimeout: 90s
  insecureSkipVerify: true
