apiVersion: v1
kind: Secret
metadata:
  name: client-app-secrets
type: Opaque
stringData:
  SECRET_KEY_BASE: "18ccca5a73c3ba1972644be68639dc5ed06e2dc62ceae5fd01170a63ac7df8f87a7224b098dee1c971d25089174d7e711c6f6c7ba0a14592129c4cea472d3d84"
  RAILS_ENV: development
  DB_HOST: db
  DB_USERNAME: postgres
  DB_PASSWORD: postgres
  DB_DATABASE: oauth_client
  OAUTH_HOST: http://accounts.lalit.local
  OAUTH_CLIENT_ID: web-frontend-app-client-id
  OAUTH_CLIENT_SECRET: web-frontend-app-client-secret
  KAFKA_BROKERS: kafka:9092