auth:
  adminUser: admin
  adminPassword: admin

replicaCount: 1

resources:
  requests:
    memory: 3Gi
    cpu: 500m
  limits:
    memory: 3Gi
    cpu: 1000m

service:
  type: ClusterIP

ingress:
  enabled: false