app:
  name: oauth-audit-app
  replicas: 1
  image:
    repository: oauth-audit-app
    tag: local
  containerPort: 3000
  env:
    RAILS_ENV: development
    KAFKA_BROKERS: kafka.services.svc.cluster.local:9092
    DB_DATABASE: oauth_audit
  secrets:
    DB_HOST: postgresql.services.svc.cluster.local
    DB_USERNAME: postgres
    DB_PASSWORD: postgres
    SECRET_KEY_BASE: "18ccca5a73c3ba1972644be68639dc5ed06e2dc62ceae5fd01170a63ac7df8f87a7224b098dee1c971d25089174d7e711c6f6c7ba0a14592129c4cea472d3d84"
  ingress:
    enabled: true
    host: audit.lalit.local
  dbMigrate:
    enabled: true