apiVersion: v2
name: rails-app
description: Helm chart for Rails applications
type: application
version: 0.1.0
appVersion: "1.0"

# Install postgresql
# helm install pgsql bitnami/postgresql \
#   --set auth.database=oauth_client_development \
#   --set auth.username=postgres \
#   --set auth.password=postgres \
#   --set primary.service.port=5432 \
#   --set primary.persistence.enabled=true \
#   --set primary.persistence.size=8Gi

# Install Kafka
# helm install kafka bitnami/kafka \
#   --set replicaCount=1 \
#   --set zookeeper.enabled=true \
#   --set kraft.enabled=false \
#   --set auth.enabled=false \
#   --set listeners.client.protocol=PLAINTEXT \
#   --set service.port=9092

# Install Nginx
# helm install nginx ingress-nginx/ingress-nginx \
#   --set controller.minReadySeconds=10 \
#   --set controller.progressDeadlineSeconds=60

# Installation Commands
# helm install oauth-client helm/rails-app -f helm/rails-app/values-client.yaml
# helm upgrade oauth-client helm/rails-app -f helm/rails-app/values-client.yaml
# 
# helm install oauth-idp helm/rails-app -f helm/rails-app/values-idp.yaml
# helm upgrade oauth-idp helm/rails-app -f helm/rails-app/values-idp.yaml
# 
# helm install oauth-client-kafka-consumer helm/rails-app -f helm/rails-app/values-client-kafka-consumer.yaml
# helm upgrade oauth-client-kafka-consumer helm/rails-app -f helm/rails-app/values-client-kafka-consumer.yaml

# Useful Debug commands
# kubectl port-forward svc/oauth-client-app-service 3001:80
# kubectl port-forward svc/oauth-idp-app-service 3001:80