# Install below plugin first before using helmfile apply --debug
# helm plugin install https://github.com/databus23/helm-diff

# Useful commands
# helmfile -l name=oauth-idp apply -f helm/helmfile.yaml 
# helmfile -l name=oauth-client apply -f helm/helmfile.yaml
# helmfile -l name=oauth-client-kafka apply -f helm/helmfile.yaml
# helmfile -l name=oauth-audit-kafka apply -f helm/helmfile.yaml
# helmfile -l name=oauth-notification-kafka apply -f helm/helmfile.yaml

# Restart services
# kubectl rollout restart deployment oauth-idp-app -n oauth-apps

# kubectl rollout restart deployment oauth-client-app -n oauth-apps
# kubectl rollout restart deployment oauth-client-kafka-consumer -n oauth-apps

# kubectl rollout restart deployment oauth-audit-app -n oauth-apps
# kubectl rollout restart deployment oauth-audit-kafka-consumer -n oauth-apps

# kubectl rollout restart deployment oauth-notification-app -n oauth-apps
# kubectl rollout restart deployment oauth-notification-kafka-consumer -n oauth-apps

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  # - name: ingress-nginx
  #   url: https://kubernetes.github.io/ingress-nginx
  - name: traefik
    url: https://traefik.github.io/charts

releases:
  # - name: ingress-nginx
  #   namespace: ingress-nginx
  #   chart: ingress-nginx/ingress-nginx
  #   version: 4.12.2
  #   values:
  #     - controller:
  #         minReadySeconds: 10
  #         progressDeadlineSeconds: 60
  
  - name: traefik
    namespace: traefik
    createNamespace: true
    chart: traefik/traefik
    values:
      - values/values-traefik.yaml

  - name: postgresql
    namespace: services
    chart: bitnami/postgresql
    version: 16.7.4
    values:
      - values/values-postgresql.yaml

  - name: kafka
    namespace: services
    chart: bitnami/kafka
    version: 26.8.2
    values:
      - values/values-kafka.yaml

  - name: keycloak
    namespace: services
    chart: bitnami/keycloak
    version: 21.2.1
    values:
      - values/values-keycloak.yaml
          
  - name: oauth-client
    chart: ./rails-app
    namespace: oauth-apps
    values:
      - values/values-client.yaml
  
  - name: oauth-client-kafka
    chart: ./rails-app
    namespace: oauth-apps
    values:
      - values/values-client-kafka.yaml

  - name: oauth-idp
    chart: ./rails-app
    namespace: oauth-apps
    values:
      - values/values-idp.yaml

  - name: oauth-audit
    chart: ./rails-app
    namespace: oauth-apps
    values:
      - values/values-audit.yaml
  
  - name: oauth-audit-kafka
    chart: ./rails-app
    namespace: oauth-apps
    values:
      - values/values-audit-kafka.yaml

  - name: oauth-notification
    chart: ./rails-app
    namespace: oauth-apps
    values:
      - values/values-notification.yaml
  
  - name: oauth-notification-kafka
    chart: ./rails-app
    namespace: oauth-apps
    values:
      - values/values-notification-kafka.yaml

  - name: tls-secret
    chart: ./tls-secret
    namespace: oauth-apps