apiVersion: v1
kind: Secret
metadata:
  name: lalit-local-tls
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "certs/lalit.local.crt" | b64enc }}
  tls.key: {{ .Files.Get "certs/lalit.local.key" | b64enc }}
